### ISSUE TITLE
wireshark-chmodbpf asking for password

### ISSUE THREAD

**Issue by dangayle** [schollz/howmanypeoplearearound#11]
After the Handbrake fiasco, I'm pretty much not interested in giving an installer my password. Is there a way around this?

![screen shot 2017-05-18 at 11 15 14 am](https://cloud.githubusercontent.com/assets/129611/26217244/8920685e-3bbb-11e7-966a-5676f5337e44.png)

**Comment by ansell** [comment]
Unfortunately, at some point you will need to give sudo a password, as you need to change the permissions on /dev/bpf* so that you don't need to run Wireshark/etc. as root.

If you are paranoid about installer passwords, you probably don't want to run Wireshark though, given the extra attack surface area that it opens up.

**Comment by dangayle** [comment]
I'm sure I'll give up caring in a few weeks, like most people who just want to get stuff done. :p

-- Dan

**Comment by cclauss** [comment]
@dangayle You can try the Docker approach.  Can we close this issue or do you see an alternative resolution?

**Comment by dangayle** [comment]
Oh, docker. I didn't even think of that. Go ahead and close.

-- Dan
